config/routes.rb
Rails.application.routes.draw do
  get 'resume/', to: 'pages#resume', as: 'resume'
  get 'photography/', to: 'pages#photography', as: 'photography'
  get 'about/', to: 'pages#about', as: 'about' 

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


	def index

	end

	def resume
		@main = "Resume"
	end

	def photography
		@main = "Photography"
	end

	def about
		@main = "About"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title.presence || "The Personal Site of Ben Granas"%></title>
    <meta name="description" content="The personal site, portfolio, and resume of Ben Granas">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/7ff43fbcaf.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,700,700i" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- favicon -->
		<%= favicon_link_tag %>

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-103582002-1', 'auto');
		  ga('send', 'pageview');

		</script>

    <!-- ************ FACEBOOK OPEN GRAPH TAGS ***************** -->
    <meta property="og:url"  content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="<%= @page_title.presence || "BenGranas.com | The personal site of Ben Granas" %>"/>
    <meta property="og:description" content="<%= @meta_description.presence || "The personal site, portfolio, and resume of Ben Granas" %>"/>
    <meta property="og:image" content="<%= image_url("Ben-Granas-logo.jpg") %>"/>
    <meta property="og:site_name" content="BenGranas.com"/>

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="BenGranas.com">
    <meta name="twitter:title" content="<%= @page_title.presence || "BenGranas.com | The personal site of Ben Granas" %>">
    <meta name="twitter:description" content="<%= @meta_description.presence || "The personal site, portfolio, and resume of Ben Granas" %>">
    <meta name="twitter:image:src" content="<%= image_url("Ben-Granas-logo.jpg") %>">
    
  </head>

  <body>
	<div class="nav-container">
		<div class="nav-right">
			<ul class="nav-list">
				<li class="nav-item"><span><%= link_to resume_url do %>Resume<% end %></span></li>
				<li class="nav-item"><span><%= link_to photography_url do %>Photography<% end %></span></li>
				<li class="nav-item"><span><%= link_to about_url do %>About<% end %></span></li>
			</ul>
		</div>
	</div>

	<% if @main %>
		<div class="pages-hero">
			<h1><%= @main %></h1>
		</div>
	<% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container-fluid lower">
	<div class="row">
		<div class="col-sm-12 col-md-5">
			<div class="photo-container">
				<%= image_tag('Ben-Granas-headshot.jpg', class: 'headshot') %>
			</div>
		</div>
		<div class="col-sm-12 col-md-7 first-xs last-md">
			<div class="text-container" itemscope itemtype="http://schema.org/Person">
				<h2>Hi, I'm Ben Granas.</h2>
				<p>I'm a builder, marketer, product manager, traveler, photographer, and life-long learner.</p>
				<p>I love creating new tools and experiences. I currently reside in Los Angeles, CA.</p>
				<p>Get in touch through the links below, or send an email to ben [at] bengranas [dot] com.</p>
			</div>
			<div class="row">
				<div class="col-xs-3 col-md-2 text-center">
					<a href="https://www.linkedin.com/in/ben-granas-142395a" target="_blank"><i class="fa fa-linkedin-square fa-3x"></i></a>
				</div>
				<div class="col-xs-3 col-md-2 text-center">
					<a href="https://github.com/bgranas" target="_blank"><i class="fa fa-github fa-3x"></i></a>
				</div>
				<div class="col-xs-3 col-md-2 text-center">
					<a href="https://angel.co/ben-granas" target="_blank"><i class="fa fa-angellist fa-3x"></i></a>
				</div>
				<div class="col-xs-3 col-md-2 text-center">
					<a href="mailto:ben@bengranas.com"><i class="fa fa-envelope-o fa-3x"></i></a>
				</div>
			</div>
		</div>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<div class="background-cover">
	<div class="name-row">
		<div class="name-holder">
			<div class="left-border"></div>
			<h1 class="name">
				<span class="firstn">Ben</span>
				<span class="lastn">Granas</span>
			</h1>
			<div class="right-border"></div>
		</div>
	</div>
	<div class="img-credits">
		<i class="fa fa-map-marker fa-lg"></i>
		<span>Atacama Desert, Chile</span>
	</div>
</div>

app/views/pages/photography.html.erb
<div class="container-fluid photography">
	<div class="row">
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Lost-in-the-Desert-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Mountain-Climbing-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('High-Desert-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Danger-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Desert-Cat-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Mountain-Views-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Sunsets-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Mountain-Reflections-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Tropic-Capricorn-Atacama.jpg') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Atacama Desert, Chile</span>
			</div>
		</div>
		<div class="col-md-12 col-lg-6 img-col">
			<div class="image-container">
				<%= image_tag('Life-on-Mars.jpg', class: 'vert') %>
			</div>
			<div class="img-credits">
				<i class="fa fa-map-marker fa-lg"></i>
				<span>Sahara Desert, Morocco</span>
			</div>
		</div>
	</div>

</div>